### ISSUE TITLE
issue melacha sensor is off by ~40 minutes

### ISSUE THREAD

**Issue by rafiw** [royi1000/py-libhdate#39]
Hi,
i'm using the jewish calendar in home assistance.
my primary usage is the issur melacha sensor in order to automate things.
the sensor to to early when shabbes starts and ends.
you can see that the sensor got off at 19:52 but shabbes was over at ~20:30
![image](https://user-images.githubusercontent.com/3034707/59968482-2f466200-9543-11e9-85a6-675d78d3cb80.png)
the Jewish Calendar Upcoming Candle Lighting sensor are accurate
![image](https://user-images.githubusercontent.com/3034707/59968535-c01d3d80-9543-11e9-8cfa-cd20120fecdd.png)

**Comment by mikeage** [comment]
I'm seeing the same thing... from the code, it looks like it should update at the `three_stars` time (although there is a note to respect the values of havdala), but it seems like it's doing this far too early.
