### ISSUE TITLE
Please file a release again

### ISSUE THREAD

**Issue by onkelbeh** [royi1000/py-libhdate#44]
Hi,

I would like to use your integration in my [Gentoo Overlay for Home Assistant](https://github.com/onkelbeh/HomeAssistantRepository).
Therefor I need a release file in tar.gz format.
Home Assistant currently requires: `hdate==0.9.3`
This one exists at Pypi, but only in wheel format, cannot use this.
On [Github](https://github.com/royi1000/py-libhdate/releases) I can only find `hdate-0.9.2`

If you want to take a look, you can find the outdated release at [Hdate](https://github.com/onkelbeh/HomeAssistantRepository/tree/master/dev-python/hdate)

A release on Github would be OK, but a Pypi tar.gz release **would be preferred**, because this could take use of Gentoo's mirror system.

Thanks
 \B.

**Comment by royi1000** [comment]
created v0.9.3 github release

**Comment by royi1000** [comment]
@tsvi please update pypi

**Comment by tsvi** [comment]
Done. I'll be careful in the future to releease source + wheel.

**Comment by onkelbeh** [comment]
Thanks,

included it yesterday:

https://github.com/onkelbeh/HomeAssistantRepository/commit/659c0c7c092975516bbb2756f64e20f85ddf74f5
